-- =============================================
-- Author:		Javier
-- Create date: June 2012
-- Description:	<Description,,>
-- =============================================
CREATE PROCEDURE [Import].[Insert_CMS_Forecast]
	
AS
BEGIN
	
	SET NOCOUNT ON;

	INSERT INTO [dbo].MARS_CMS_FORECAST
	SELECT 	
		FC.FC_DATE					AS 'REP_DATE'	, 
		FC.COUNTRY					AS 'COUNTRY'	, 
		SLG.CMS_LOCATION_GROUP_ID					, 
		CC.CAR_CLASS_ID, 
		SUM
			(
				FC.CONSTRAINED_BOOKED			+ 
				FC.SIG_CONSTRAINED_INCR			+ 
				FC.NONSIG_CONSTRAINED_INCR
			)						AS 'CONSTRAINED', 
		SUM
			(
				FC.PRICEABLE_UNCONSTRAINED		+ 
				FC.YIELDABLE_UNCONSTRAINED		+ 
				FC.FREESELL_UNCONSTRAINED		+ 
				FC.INTERPOOL_UNCONSTRAINED		+ 
				FC.UNCONSTRAINED_INCREMENTAL
			)						AS 'UNCONSTRAINED', 
		SUM
			(
				FC.USABLE_FLEET
			)						AS 'FLEET', 
		SUM
			(
				FC.PRICEABLE_BOOKED				+ 
				FC.YIELDABLE_BOOKED				+ 
				FC.FREESELL_BOOKED				+ 
				FC.INTERPOOL_BOOKED
			)						AS 'RESERVATIONS_BOOKED'
		, NULL						AS 'CURRENT_ONRENT'
		, NULL						AS 'FORECASTED_RETURNS'
		, NULL						AS 'ONRENT_LY'
		, NULL						AS 'AVAILABLE_FLEET'
		, NULL						AS 'OPERATIONAL_FLEET'
		, NULL						AS 'OPERATIONAL_FLEET_S1'
		, NULL						AS 'OPERATIONAL_FLEET_S2'
		, NULL						AS 'OPERATIONAL_FLEET_S3'
		, NULL						AS 'OPERATIONAL_FLEET_AV'
		, NULL						AS 'TOTAL_FLEET'
		
	FROM 
		MARS_CMS_Forecast_cle FC
		
	INNER JOIN dbo.vw_Mapping_CMS_Location_Group SLG ON 
			SLG.COUNTRY					= FC.COUNTRY 
		AND SLG.CMS_LOCATION_GROUP		= FC.LOCATION_GROUP_CODE
	
	INNER JOIN dbo.vw_Mapping_CarClass CC ON 
			CC.COUNTRY					= FC.COUNTRY 
		AND CC.CAR_CLASS				= FC.CAR_CLASS

	GROUP BY 
		FC.FC_DATE, FC.COUNTRY, SLG.CMS_POOL_ID, 
		SLG.CMS_LOCATION_GROUP_ID, CC.CAR_SEGMENT_ID, 
		CC.CAR_CLASS_GROUP_ID, CC.CAR_CLASS_ID
    
END