CREATE TABLE [dbo].[FLEET_EUROPE_ACTUAL_QUERY_TABLE] (
    [IMPORTTIME]        DATETIME        NULL,
    [BASEOP]            NUMERIC (18, 2) NULL,
    [BDDAYS]            INT             NULL,
    [CAPCOST]           NUMERIC (18, 2) NULL,
    [CAPDATE]           DATETIME        NULL,
    [CARHOLD1]          VARCHAR (5)     NULL,
    [COLOR]             VARCHAR (5)     NULL,
    [DAYSAREA]          INT             NULL,
    [DAYSCTRY]          INT             NULL,
    [DAYSMOVE]          INT             NULL,
    [DAYSREV]           INT             NULL,
    [DEPAMT]            NUMERIC (18, 2) NULL,
    [DEPSTAT]           VARCHAR (5)     NULL,
    [DRVNAME]           VARCHAR (25)    NULL,
    [DUEAREA]           VARCHAR (10)    NULL,
    [DUEDATE]           DATETIME        NULL,
    [DUETIME]           DATETIME        NULL,
    [DUEWWD]            VARCHAR (10)    NULL,
    [IDATE]             DATETIME        NULL,
    [LICENSE]           VARCHAR (25)    NULL,
    [LSTAREA]           VARCHAR (10)    NULL,
    [LSTDATE]           DATETIME        NULL,
    [LSTMLG]            NUMERIC (18, 2) NULL,
    [LSTNO]             VARCHAR (25)    NULL,
    [LSTOORC]           VARCHAR (10)    NULL,
    [LSTTIME]           DATETIME        NULL,
    [LSTTYPE]           VARCHAR (10)    NULL,
    [LSTWWD]            VARCHAR (10)    NULL,
    [MMDAYS]            INT             NULL,
    [MODDESC]           VARCHAR (50)    NULL,
    [MODEL]             VARCHAR (10)    NULL,
    [MODGROUP]          VARCHAR (25)    NULL,
    [MOVETYPE]          VARCHAR (10)    NULL,
    [MSODATE]           DATETIME        NULL,
    [OPERDAYS]          INT             NULL,
    [OPERSTAT]          VARCHAR (50)    NULL,
    [OWNAREA]           VARCHAR (10)    NULL,
    [OWNWWD]            VARCHAR (10)    NULL,
    [PONO]              VARCHAR (25)    NULL,
    [PREVWWD]           VARCHAR (10)    NULL,
    [RADATE]            DATETIME        NULL,
    [RALOC]             VARCHAR (10)    NULL,
    [RC]                VARCHAR (5)     NULL,
    [SDATE]             DATETIME        NULL,
    [SERIAL]            VARCHAR (25)    NOT NULL,
    [SPROCDAT]          DATETIME        NULL,
    [TERMDAYS]          INT             NULL,
    [UNIT]              VARCHAR (10)    NULL,
    [VC]                VARCHAR (5)     NULL,
    [VEHCLAS]           VARCHAR (5)     NULL,
    [VEHTYPE]           VARCHAR (5)     NULL,
    [VENDNBR]           VARCHAR (50)    NULL,
    [VISMODEL]          VARCHAR (50)    NULL,
    [COUNTRY]           VARCHAR (50)    NULL,
    [POOL]              AS              ([dbo].[fnGetPoolForLocation]([LSTWWD])),
    [LOC_GROUP]         AS              ([dbo].[fnGetLocGroupForLocation]([LSTWWD])),
    [CARVAN]            AS              ([dbo].[fnGetCarVanForVcAndOwnwwd]([VC],[OWNWWD])),
    [CAR_CLASS]         AS              ([dbo].[fnGetCarClassForVcAndOwnwwd-TEMP]([VC],[OWNWWD])),
    [FLEET_RAC_TTL]     AS              ([dbo].[fnGetFleetRACTTLForOwnareaAndLstwwd]([OWNAREA],[LSTWWD])),
    [FLEET_RAC_OPS]     AS              ([dbo].[fnGetFleetRACOPSForCarhold1AndDepstatAndOperstatAndOwnareaAndLstwwdAndDuewwdAndVehclas]([CARHOLD1],[DEPSTAT],[OPERSTAT],[OWNAREA],[LSTWWD],[DUEWWD],[VEHCLAS])),
    [FLEET_CARSALES]    AS              ([dbo].[fnGetFleetCarsalesForOwnarea]([OWNAREA])),
    [FLEET_LICENSEE]    AS              ([dbo].[fnGetFleetLicenseeForOwnarea]([OWNAREA])),
    [FLEET_HOD]         AS              ([dbo].[fnGetFleetHertzOnDemandForOwnarea]([OWNAREA])),
    [FLEET_ADV]         AS              ([dbo].[fnGetFleetAdvantageForOwnareaAndLstwwd]([OWNAREA],[LSTWWD])),
    [TOTAL_FLEET]       AS              ([dbo].[fnGetTotalFleetForLicenseAndOwnwwd]([LICENSE],[OWNWWD])),
    [CARSALES]          AS              ([dbo].[fnGetCarSalesForOwnarea]([OWNAREA])),
    [CARHOLD_H]         AS              (case when [CARHOLD1]='H' then (1) else (0) end),
    [CARHOLD_L]         AS              (case when [CARHOLD1]='L' then (1) else (0) end),
    [CU]                AS              (case when [OPERSTAT]='CU' then (1) else (0) end),
    [HA]                AS              (case when [OPERSTAT]='HA' then (1) else (0) end),
    [HL]                AS              (case when [OPERSTAT]='HL' then (1) else (0) end),
    [LL]                AS              (case when [OPERSTAT]='LL' then (1) else (0) end),
    [NC]                AS              (case when [OPERSTAT]='NC' then (1) else (0) end),
    [PL]                AS              (case when [OPERSTAT]='PL' then (1) else (0) end),
    [TC]                AS              (case when [OPERSTAT]='TC' then (1) else (0) end),
    [SV]                AS              (case when [OPERSTAT]='SV' then (1) else (0) end),
    [WS]                AS              (case when [OPERSTAT]='WS' then (1) else (0) end),
    [WS_NONRAC]         AS              ([dbo].[fnGetWsNonracForOperstatAndOwnarea]([OPERSTAT],[OWNAREA])),
    [OPERATIONAL_FLEET] AS              ([dbo].[fnGetOperationalFleetForOperstat]([OPERSTAT])),
    [BD]                AS              (case when [OPERSTAT]='BD' then (1) else (0) end),
    [MM]                AS              (case when [OPERSTAT]='MM' then (1) else (0) end),
    [TW]                AS              (case when [OPERSTAT]='TW' then (1) else (0) end),
    [TB]                AS              (case when [OPERSTAT]='TB' then (1) else (0) end),
    [WS_RAC]            AS              ([dbo].[fnGetWsRacForOperstatAndOwnarea]([OPERSTAT],[OWNAREA])),
    [AVAILABLE_TB]      AS              (case when [OPERSTAT]='RT' AND [MOVETYPE]<>'R-O' AND [CAPDATE]<=getdate() then (1) else (0) end),
    [FS]                AS              (case when [OPERSTAT]='FS' then (1) else (0) end),
    [RL]                AS              (case when [OPERSTAT]='RL' then (1) else (0) end),
    [RP]                AS              (case when [OPERSTAT]='RP' then (1) else (0) end),
    [TN]                AS              (case when [OPERSTAT]='TN' then (1) else (0) end),
    [AVAILABLE_FLEET]   AS              ([dbo].[fnGetAvailableFleetForOperstat]([OPERSTAT])),
    [RT]                AS              (case when [OPERSTAT]='RT' AND ([MOVETYPE]<>'R-O' OR [MOVETYPE] IS NULL) then (1) else (0) end),
    [SU]                AS              (case when [OPERSTAT]='SU' then (1) else (0) end),
    [GOLD]              AS              ((0)),
    [PREDELIVERY]       AS              ((0)),
    [OVERDUE]           AS              ([dbo].[fnGetOverdueForOperstatAndMovetypeAndDuedate]([OPERSTAT],[MOVETYPE],[DUEDATE])),
    [ON_RENT]           AS              ([dbo].[fnGetOnrentForOperstatAndMovetypeAndDuedate]([OPERSTAT],[MOVETYPE],[DUEDATE])),
    [CI_HOURS]          AS              ([dbo].[fnGetFleetCIHoursForOperstatAndMovetypeAndImporttimeAndDuedateAndDuetime]([OPERSTAT],[MOVETYPE],[IMPORTTIME],[DUEDATE],[DUETIME],[LSTOORC],[DUEWWD])),
    [CI_HOURS_OFFSET]   AS              ([dbo].[fnGetFleetCIHoursOffsetForDuewwdOperstatAndMovetypeAndImporttimeAndDuedateAndDuetime]([DUEWWD],[OPERSTAT],[MOVETYPE],[IMPORTTIME],[DUEDATE],[DUETIME],[LSTOORC])),
    [CI_DAYS]           AS              ([dbo].[fnGetFleetCIDaysForOperstatAndMovetypeAndImporttimeAndDuedate]([OPERSTAT],[MOVETYPE],[IMPORTTIME],[DUEDATE])),
    CONSTRAINT [FK_FLEET_EUROPE_ACTUAL_QUERY_TABLE_OPERSTATS] FOREIGN KEY ([OPERSTAT]) REFERENCES [dbo].[OPERSTATS] ([operstat_name])
);



