CREATE TABLE [dbo].[MARS_CMS_FORECAST_ADJUSTMENT] (
    [REP_DATE]              DATETIME       NOT NULL,
    [COUNTRY]               VARCHAR (10)   NOT NULL,
    [CMS_LOCATION_GROUP_ID] INT            NOT NULL,
    [CAR_CLASS_ID]          INT            NOT NULL,
    [ADJUSTMENT_TD]         NUMERIC (9, 2) NULL,
    [ADJUSTMENT_BU1]        NUMERIC (9, 2) NULL,
    [ADJUSTMENT_BU2]        NUMERIC (9, 2) NULL,
    [ADJUSTMENT_RC]         NUMERIC (9, 2) NULL,
    CONSTRAINT [FK_MARS_CMS_FORECAST_ADJUSTMENT_CAR_GROUPS] FOREIGN KEY ([CAR_CLASS_ID]) REFERENCES [dbo].[CAR_GROUPS] ([car_group_id]) ON DELETE CASCADE,
    CONSTRAINT [FK_MARS_CMS_FORECAST_ADJUSTMENT_CMS_LOCATION_GROUPS] FOREIGN KEY ([CMS_LOCATION_GROUP_ID]) REFERENCES [dbo].[CMS_LOCATION_GROUPS] ([cms_location_group_id]) ON DELETE CASCADE
);




GO
CREATE NONCLUSTERED INDEX [RepDate]
    ON [dbo].[MARS_CMS_FORECAST_ADJUSTMENT]([REP_DATE] ASC);


GO
CREATE NONCLUSTERED INDEX [Rep_DateIncludedColumns]
    ON [dbo].[MARS_CMS_FORECAST_ADJUSTMENT]([REP_DATE] ASC)
    INCLUDE([CMS_LOCATION_GROUP_ID], [CAR_CLASS_ID], [ADJUSTMENT_TD], [ADJUSTMENT_BU1], [ADJUSTMENT_BU2], [ADJUSTMENT_RC]);


GO
CREATE CLUSTERED INDEX [LocationGroupId]
    ON [dbo].[MARS_CMS_FORECAST_ADJUSTMENT]([CMS_LOCATION_GROUP_ID] ASC);


GO
CREATE NONCLUSTERED INDEX [Country]
    ON [dbo].[MARS_CMS_FORECAST_ADJUSTMENT]([COUNTRY] ASC);


GO
CREATE NONCLUSTERED INDEX [CarClassId]
    ON [dbo].[MARS_CMS_FORECAST_ADJUSTMENT]([CAR_CLASS_ID] ASC);

