CREATE TABLE [dbo].[NONPOOL_EU_LICENCEE] (
    [OWNCTRY]  VARCHAR (2)  NULL,
    [LSTCTRY]  VARCHAR (2)  NULL,
    [LSTWWD]   VARCHAR (10) NULL,
    [VC]       VARCHAR (5)  NULL,
    [UNIT]     VARCHAR (20) NULL,
    [LICENSE]  VARCHAR (20) NULL,
    [MODEL]    VARCHAR (10) NULL,
    [MODDESC]  VARCHAR (50) NULL,
    [MOVETYPE] VARCHAR (10) NULL
);

