-- =============================================
-- Author:		Javier
-- Create date: June 2012
-- Description:	1) FLEET_EUROPE_OKCFILE -> FLEET_EUROPE_ACTUAL_QUERY_TABLE
-- =============================================
CREATE PROCEDURE [Import].[Insert_Fleet_Query]
@Type varchar(20)
	
AS
BEGIN
	
	SET NOCOUNT ON;

	if @Type = 'Daily'
	begin
	--SET ANSI_WARNINGS  OFF
    INSERT INTO dbo.FLEET_EUROPE_ACTUAL_QUERY_TABLE 
    (
			IMPORTTIME , 
			BASEOP,
			BDDAYS,
			CAPCOST,
			CAPDATE,
			CARHOLD1,
			COLOR,
			DAYSAREA,
			DAYSCTRY,
			DAYSMOVE,
			DAYSREV,DEPAMT,DEPSTAT,DRVNAME,DUEAREA,DUEDATE,
			DUETIME,DUEWWD,IDATE,LICENSE,LSTAREA,LSTDATE,LSTMLG,LSTNO,LSTOORC,LSTTIME,LSTTYPE,
			LSTWWD,MMDAYS,MODDESC,MODEL,MODGROUP,MOVETYPE,MSODATE,OPERDAYS,OPERSTAT,OWNAREA,OWNWWD,
			PONO,PREVWWD,RADATE,RALOC,RC,SDATE,SERIAL,SPROCDAT,TERMDAYS,UNIT,
			VC,VEHCLAS,VEHTYPE,VENDNBR,VISMODEL , COUNTRY
		)
    
    
	SELECT 
		CONVERT(datetime, DATEADD(dd, 0, DATEDIFF(dd, 0, GETDATE())) + ' 6:50:00 AM') AS IMPORTTIME, 
		BASEOP, 
		CASE WHEN BDDAYS = 0 THEN NULL ELSE BDDAYS END AS BDDAYS, 
		CAPCOST, 
		CASE WHEN CAPDATE = '12/31/9999' THEN NULL ELSE CAPDATE END AS CAPDATE,
		LEFT(CARHOLD1, 5)	AS CARHOLD1, 
		LEFT(COLOR, 5)		AS COLOR, 
		DAYSAREA, 
		DAYSCTRY, 
		DAYSMOVE, 
		DAYSREV, 
		DEPAMT, 
		LEFT(DEPSTAT, 5) AS DEPSTAT, 
		LEFT(DRVNAME, 25) AS DRVNAME, 
		LEFT(DUEAREA, 10) AS DUEAREA, 
		CASE WHEN DUEDATE = '12/31/9999' THEN NULL ELSE DUEDATE END AS DUEDATE, 
		CASE WHEN LEN(DUETIME) < 3 THEN NULL ELSE LEFT(DUETIME, LEN(DUETIME) -2) + ':' + RIGHT(DUETIME, 2) END AS DUETIME, 
		CASE WHEN DUEWWD = '' THEN NULL ELSE DUEWWD END AS DUEWWD,
		CASE WHEN IDATE = '12/31/9999' THEN NULL ELSE IDATE END AS IDATE, 
		LEFT(LICENSE, 25)	AS LICENSE, 
		LEFT(LSTAREA, 10)	AS LSTAREA,
		CASE WHEN LSTDATE = '12/31/9999' THEN NULL ELSE LSTDATE END AS LSTDATE,
		LSTMLG, 
		LEFT(LSTNO, 25)		AS LSTNO,
		LEFT(LSTOORC, 10)	AS LSTOORC, 
		CASE WHEN LEN(LSTTIME) < 3 THEN NULL ELSE LEFT(LSTTIME, LEN(LSTTIME) -2) + ':' + RIGHT(LSTTIME, 2) END AS LSTTIME, 
		LEFT(LSTTYPE, 10)	AS LSTTYPE, 
		LEFT(LSTWWD, 10)	AS LSTWWD, 
		MMDAYS, 
		LEFT(MODDESC, 50)	AS MODDESC, 
		LEFT(MODEL, 10)		AS MODEL,
		LEFT(MODGROUP, 25)	AS MODGROUP, 
		LEFT (RTRIM(LSTTYPE) + '-' + RTRIM(LSTOORC), 10) AS MOVETYPE, 
		CASE WHEN MSODATE = '12/31/9999' THEN NULL ELSE MSODATE END AS MSODATE,
		OPERDAYS, 
		LEFT (OPERSTAT, 10) AS OPERSTAT, 
		LEFT (OWNAREA, 10)	AS OWNAREA, 
		LEFT (OWNWWD, 10)	AS OWNWWD, 
		LEFT (PONO, 25)		AS PONO, 
		LEFT (PREVWWD, 10)	AS PREVWWD,
		CASE WHEN RADATE = '12/31/9999' THEN NULL ELSE RADATE END AS RADATE, 
		LEFT (RALOC, 10)	AS RALOC, 
		LEFT (LTRIM(RTRIM(RC)), 5) AS RC,
		CASE WHEN SDATE = '12/31/9999' THEN NULL ELSE SDATE END AS SDATE, 
		LEFT (LTRIM(RTRIM(SERIAL)), 25) AS SERIAL, 
		CASE WHEN SPROCDAT = '12/31/9999' THEN NULL ELSE SPROCDAT END AS SPROCDAT, 
		TERMDAYS, 
		RIGHT(LTRIM(RTRIM(CONVERT(varchar, UNIT))), 7) AS UNIT, 
		LEFT(LTRIM(RTRIM(VC)), 5) AS VC,
		LEFT(VEHCLAS, 5)	AS VEHCLAS,
		LEFT(VEHTYPE, 5)	AS VEHTYPE,
		LEFT(VENDNBR, 10)	AS VENDNBR, 
		LEFT(VISMODEL, 25)	AS VISMODEL,
		CTRYCODE			AS COUNTRY
	FROM 
		dbo.FLEET_EUROPE_OKCFILE
	--SET ANSI_WARNINGS  ON
	END
END