-- =============================================
-- Author:		Javier
-- Create date: June 2012
-- Description:	<Description,,>
-- =============================================
CREATE PROCEDURE [Import].[Update_Fleet_Query]
@Type varchar(20)
	
AS
BEGIN
	
	SET NOCOUNT ON;

if @Type = 'Hourly'
begin
	SET ANSI_WARNINGS  OFF
    UPDATE dbo.FLEET_EUROPE_ACTUAL_QUERY_TABLE SET 
		BASEOP		= okc.BASEOP,
		BDDAYS		= okc.BDDAYS,
		CAPCOST		= okc.CAPCOST,
		CAPDATE		= okc.CAPDATE,
		CARHOLD1	= okc.CARHOLD1,
		COLOR		= okc.COLOR,
		DAYSAREA	= okc.DAYSAREA,
		DAYSCTRY	= okc.DAYSCTRY,
		DAYSMOVE	= okc.DAYSMOVE,
		DAYSREV		= okc.DAYSREV,
		DEPAMT		= okc.DEPAMT,
		DEPSTAT		= okc.DEPSTAT,
		DRVNAME		= okc.DRVNAME,
		DUEAREA		= okc.DUEAREA,
		DUEDATE		= okc.DUEDATE,
		DUETIME		= okc.DUETIME,
		DUEWWD		= okc.DUEWWD,
		IDATE		= okc.IDATE,
		LICENSE		= okc.LICENSE,
		LSTAREA		= okc.LSTAREA,
		LSTDATE		= okc.LSTDATE,
		LSTMLG		= okc.LSTMLG,
		LSTNO		= okc.LSTNO,
		LSTOORC		= okc.LSTOORC,
		LSTTIME		= okc.LSTTIME,
		LSTTYPE		= okc.LSTTYPE,
		LSTWWD		= okc.LSTWWD,
		MMDAYS		= okc.MMDAYS,
		MODDESC		= okc.MODDESC,
		MODEL		= okc.MODEL,
		MODGROUP	= okc.MODGROUP,
		MOVETYPE	= okc.MOVETYPE,
		MSODATE		= okc.MSODATE,
		OPERDAYS	= okc.OPERDAYS,
		OPERSTAT	= okc.OPERSTAT,
		OWNAREA		= okc.OWNAREA,
		OWNWWD		= okc.OWNWWD,
		PONO		= okc.PONO,
		PREVWWD		= okc.PREVWWD,
		RADATE		= okc.RADATE,
		RALOC		= okc.RALOC,
		RC			= okc.RC,
		SDATE		= okc.SDATE,
		SPROCDAT	= okc.SPROCDAT,
		TERMDAYS	= okc.TERMDAYS,
		UNIT		= okc.UNIT,
		VC			= okc.VC,
		VEHCLAS		= okc.VEHCLAS,
		VEHTYPE		= okc.VEHTYPE,
		VENDNBR		= okc.VENDNBR,
		VISMODEL	= okc.VISMODEL
	FROM 
		(
			SELECT 			
				BASEOP, 
				CASE WHEN BDDAYS = 0 THEN NULL ELSE BDDAYS END AS BDDAYS, 
				CAPCOST, 
				CASE WHEN CAPDATE = '12/31/9999' THEN NULL ELSE CAPDATE END AS CAPDATE,
				LEFT(CARHOLD1, 5) AS CARHOLD1, 
				LEFT(COLOR, 5) AS COLOR, 
				DAYSAREA, 
				DAYSCTRY, 
				DAYSMOVE, 
				DAYSREV, 
				DEPAMT, 
				LEFT(DEPSTAT, 5) AS DEPSTAT, 
				LEFT(DRVNAME, 25) AS DRVNAME, 
				LEFT(DUEAREA, 10) AS DUEAREA, 
				CASE WHEN DUEDATE = '12/31/9999' THEN NULL ELSE DUEDATE END AS DUEDATE, 
				CASE WHEN LEN(DUETIME) < 3 THEN NULL ELSE LEFT(DUETIME, LEN(DUETIME) -2) + ':' + RIGHT(DUETIME, 2) END AS DUETIME, 
				CASE WHEN DUEWWD = '' THEN NULL ELSE DUEWWD END AS DUEWWD,
				CASE WHEN IDATE = '12/31/9999' THEN NULL ELSE IDATE END AS IDATE, 
				LEFT(LICENSE, 25) AS LICENSE, 
				LEFT(LSTAREA, 10) AS LSTAREA,
				CASE WHEN LSTDATE = '12/31/9999' THEN NULL ELSE LSTDATE END AS LSTDATE,
				LSTMLG, 
				LEFT(LSTNO, 25) AS LSTNO,
				LEFT(LSTOORC, 10) AS LSTOORC, 
				CASE WHEN LEN(LSTTIME) < 3 THEN NULL ELSE LEFT(LSTTIME, LEN(LSTTIME) -2) + ':' + RIGHT(LSTTIME, 2) END AS LSTTIME, 
				LEFT(LSTTYPE, 10) AS LSTTYPE, 
				LEFT(LSTWWD, 10) AS LSTWWD, 
				MMDAYS, 
				LEFT(MODDESC, 50) AS MODDESC, 
				LEFT(MODEL, 10) AS MODEL,
				LEFT(MODGROUP, 25) AS MODGROUP, 
				LEFT (RTRIM(LSTTYPE) + '-' + RTRIM(LSTOORC), 10) AS MOVETYPE, 
				CASE WHEN MSODATE = '12/31/9999' THEN NULL ELSE MSODATE END AS MSODATE,
				OPERDAYS, 
				LEFT (OPERSTAT, 10) AS OPERSTAT, 
				LEFT (OWNAREA, 10) AS OWNAREA, 
				LEFT (OWNWWD, 10) AS OWNWWD, 
				LEFT (PONO, 25) AS PONO, 
				LEFT (PREVWWD, 10) AS PREVWWD,
				CASE WHEN RADATE = '12/31/9999' THEN NULL ELSE RADATE END AS RADATE, 
				LEFT (RALOC, 10) AS RALOC, 
				LEFT (LTRIM(RTRIM(RC)), 5) AS RC,
				CASE WHEN SDATE = '12/31/9999' THEN NULL ELSE SDATE END AS SDATE, 
				LEFT (LTRIM(RTRIM(SERIAL)), 25) AS SERIAL, 
				CASE WHEN SPROCDAT = '12/31/9999' THEN NULL ELSE SPROCDAT END AS SPROCDAT, 
				TERMDAYS, 
				RIGHT(LTRIM(RTRIM(CONVERT(varchar, UNIT))), 7) AS UNIT, 
				LEFT(LTRIM(RTRIM(VC)), 5) AS VC,
				LEFT(VEHCLAS, 5) AS VEHCLAS,
				LEFT(VEHTYPE, 5) AS VEHTYPE,
				LEFT(VENDNBR, 10) AS VENDNBR, 
				LEFT(VISMODEL, 25) AS VISMODEL
			FROM 
				dbo.FLEET_EUROPE_OKCFILE
		) 
		AS okc
	WHERE
		(okc.SERIAL = dbo.FLEET_EUROPE_ACTUAL_QUERY_TABLE.SERIAL)
		AND
		(okc.OWNAREA = dbo.FLEET_EUROPE_ACTUAL_QUERY_TABLE.OWNAREA)
	SET ANSI_WARNINGS  ON	
end
END