-- =============================================
-- Author:		Javier
-- Create date: June 2012
-- Description:	<Description,,>
-- =============================================
CREATE PROCEDURE [Import].[Update_CMS_Forecast_OPERATIONAL_FLEET]
	
	@theDay			DATETIME,
	@COUNTRY		VARCHAR(5), 
	@fleetPlanID	INT
	
AS
BEGIN
	
	SET NOCOUNT ON;
	
	DECLARE @OP TABLE 
		(REP_DATE SMALLDATETIME, CMS_LOCATION_GROUP_ID INT, CAR_CLASS_ID INT, OPERATIONAL_FLEET NUMERIC(9,2))

	INSERT INTO @OP
	SELECT 
		FC.REP_DATE, 
		FC.CMS_LOCATION_GROUP_ID, 
		FC.CAR_CLASS_ID, 
		ISNULL(FC.OPERATIONAL_FLEET_AV,0) + SUM(ISNULL(FP.amount,0)) AS 'OPERATIONAL_FLEET_NEW'
	FROM
	(
		SELECT *
		FROM 
			MARS_CMS_FORECAST FC
		WHERE 
			FC.REP_DATE >= @theDay 
		AND 
			(FC.COUNTRY = @COUNTRY OR @COUNTRY IS NULL)
	) FC
	INNER JOIN
	(
		SELECT 
			PD.targetDate, PD.CMS_LOCATION_GROUP_ID, PD.car_class_id, PD.amount
		FROM 
			MARS_CMS_FleetPlanEntry PE
		INNER JOIN MARS_CMS_FleetPlanDetails PD ON PE.PKID = PD.fleetPlanEntryID
		WHERE 
			(PE.Country = @COUNTRY OR @COUNTRY IS NULL)
		AND PE.fleetPlanID = @fleetPlanID
		AND PD.targetDate >= @theDay
	) FP ON 
		FC.REP_DATE > FP.targetDate 
	AND FC.CMS_LOCATION_GROUP_ID = FP.CMS_LOCATION_GROUP_ID 
	AND FC.CAR_CLASS_ID = FP.car_class_id

	GROUP BY 
		FC.REP_DATE, FC.CMS_LOCATION_GROUP_ID, FC.CAR_CLASS_ID, FC.OPERATIONAL_FLEET_AV
	--	order by FC.REP_DATE, CMS_LOCATION_GROUP_ID, car_class_id

			--select * from @OP

	IF @fleetPlanID = 1
	-- Actual
	BEGIN
		UPDATE MARS_CMS_FORECAST SET 
			OPERATIONAL_FLEET = OP.OPERATIONAL_FLEET	
		FROM 
			MARS_CMS_FORECAST FC
		INNER JOIN @OP OP ON 
			FC.REP_DATE = OP.REP_DATE 
		AND FC.CMS_LOCATION_GROUP_ID = OP.CMS_LOCATION_GROUP_ID 
		AND FC.CAR_CLASS_ID = OP.CAR_CLASS_ID		
		WHERE 
			FC.OPERATIONAL_FLEET <> OP.OPERATIONAL_FLEET	
	END
	ELSE IF @fleetPlanID = 2
	-- Scenario 1
	BEGIN
		UPDATE MARS_CMS_FORECAST SET 
			OPERATIONAL_FLEET_S1 = OP.OPERATIONAL_FLEET	
		FROM 
			MARS_CMS_FORECAST FC
		INNER JOIN @OP OP ON 
			FC.REP_DATE = OP.REP_DATE 
		AND FC.CMS_LOCATION_GROUP_ID = OP.CMS_LOCATION_GROUP_ID 
		AND FC.CAR_CLASS_ID = OP.CAR_CLASS_ID
		WHERE 
			FC.OPERATIONAL_FLEET_S1 <> OP.OPERATIONAL_FLEET	
	END
	ELSE IF @fleetPlanID = 3
	-- Scenario 2
	BEGIN
		UPDATE MARS_CMS_FORECAST SET 
			OPERATIONAL_FLEET_S2 = OP.OPERATIONAL_FLEET	
		FROM 
			MARS_CMS_FORECAST FC
		INNER JOIN @OP OP ON 
			FC.REP_DATE = OP.REP_DATE 
		AND FC.CMS_LOCATION_GROUP_ID = OP.CMS_LOCATION_GROUP_ID 
		AND FC.CAR_CLASS_ID = OP.CAR_CLASS_ID
		WHERE 
			FC.OPERATIONAL_FLEET_S2 <> OP.OPERATIONAL_FLEET	
	END
	ELSE IF @fleetPlanID = 4
	-- Scenario 3
	BEGIN
		UPDATE MARS_CMS_FORECAST SET 
			OPERATIONAL_FLEET_S3 = OP.OPERATIONAL_FLEET	
		FROM 
			MARS_CMS_FORECAST FC
		INNER JOIN @OP OP ON 
			FC.REP_DATE = OP.REP_DATE 
		AND FC.CMS_LOCATION_GROUP_ID = OP.CMS_LOCATION_GROUP_ID 
		AND FC.CAR_CLASS_ID = OP.CAR_CLASS_ID
		WHERE 
			FC.OPERATIONAL_FLEET_S3 <> OP.OPERATIONAL_FLEET	
	END


    
END