CREATE procedure [dbo].[proc_GetNecessaryFleetExportData]
	
	@country varchar(2)
	
AS
BEGIN

	SET NOCOUNT ON;
	SELECT NF.COUNTRY, LG.CMS_POOL, LG.CMS_LOCATION_GROUP, CC.CAR_SEGMENT, CC.CAR_CLASS_GROUP, CC.CAR_CLASS
		, NF.UTILISATION AS 'Av. Fleet Util.', NF.NONREV_FLEET AS 'NonRev Op. Fleet %'
		FROM MARS_CMS_NECESSARY_FLEET NF
			INNER JOIN vw_Mapping_CMS_Location_Group LG ON LG.CMS_LOCATION_GROUP_ID = NF.CMS_LOCATION_GROUP_ID
			INNER JOIN vw_Mapping_CarClass CC ON CC.CAR_CLASS_GROUP_ID = NF.CAR_CLASS_ID
		WHERE NF.COUNTRY = @COUNTRY
		ORDER BY LG.CMS_POOL, LG.CMS_LOCATION_GROUP, CC.CAR_SEGMENT, CC.CAR_CLASS_GROUP, CC.CAR_CLASS
END