//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mars.App.Site.Administration.Mappings {
    
    
    public partial class Mappings {
        
        /// <summary>
        /// upCountries control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.UpdatePanel upCountries;
        
        /// <summary>
        /// ucCountryParameter control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Mars.App.UserControls.Phase4.Administration.Mapping.EntityParameter ucCountryParameter;
        
        /// <summary>
        /// ucCountryGrid control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Mars.App.UserControls.Phase4.Administration.Mapping.EntityGrid ucCountryGrid;
        
        /// <summary>
        /// ucCountryPopup control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Mars.App.UserControls.Phase4.Administration.Mapping.EntityPopups.CountryPopup ucCountryPopup;
        
        /// <summary>
        /// upPools control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.UpdatePanel upPools;
        
        /// <summary>
        /// ucPoolParameter control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Mars.App.UserControls.Phase4.Administration.Mapping.EntityParameter ucPoolParameter;
        
        /// <summary>
        /// ucPoolGrid control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Mars.App.UserControls.Phase4.Administration.Mapping.EntityGrid ucPoolGrid;
        
        /// <summary>
        /// ucPoolPopup control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Mars.App.UserControls.Phase4.Administration.Mapping.EntityPopups.PoolPopup ucPoolPopup;
        
        /// <summary>
        /// upLocationGroups control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.UpdatePanel upLocationGroups;
        
        /// <summary>
        /// ucLocationGroupParameters control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Mars.App.UserControls.Phase4.Administration.Mapping.EntityParameter ucLocationGroupParameters;
        
        /// <summary>
        /// ucLocationGroupGrid control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Mars.App.UserControls.Phase4.Administration.Mapping.EntityGrid ucLocationGroupGrid;
        
        /// <summary>
        /// ucLocationGroupPopup control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Mars.App.UserControls.Phase4.Administration.Mapping.EntityPopups.LocationGroupPopup ucLocationGroupPopup;
        
        /// <summary>
        /// upRegion control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.UpdatePanel upRegion;
        
        /// <summary>
        /// ucRegionParameters control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Mars.App.UserControls.Phase4.Administration.Mapping.EntityParameter ucRegionParameters;
        
        /// <summary>
        /// ucRegionGrid control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Mars.App.UserControls.Phase4.Administration.Mapping.EntityGrid ucRegionGrid;
        
        /// <summary>
        /// ucRegionPopup control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Mars.App.UserControls.Phase4.Administration.Mapping.EntityPopups.RegionPopup ucRegionPopup;
        
        /// <summary>
        /// upArea control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.UpdatePanel upArea;
        
        /// <summary>
        /// ucAreaParameters control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Mars.App.UserControls.Phase4.Administration.Mapping.EntityParameter ucAreaParameters;
        
        /// <summary>
        /// ucAreaGrid control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Mars.App.UserControls.Phase4.Administration.Mapping.EntityGrid ucAreaGrid;
        
        /// <summary>
        /// ucAreaPopup control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Mars.App.UserControls.Phase4.Administration.Mapping.EntityPopups.AreaPopup ucAreaPopup;
        
        /// <summary>
        /// upLocations control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.UpdatePanel upLocations;
        
        /// <summary>
        /// ucLocationParameters control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Mars.App.UserControls.Phase4.Administration.Mapping.EntityParameter ucLocationParameters;
        
        /// <summary>
        /// ucLocationGrid control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Mars.App.UserControls.Phase4.Administration.Mapping.EntityGrid ucLocationGrid;
        
        /// <summary>
        /// ucLocationPopup control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Mars.App.UserControls.Phase4.Administration.Mapping.EntityPopups.LocationPopup ucLocationPopup;
        
        /// <summary>
        /// upCarSegments control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.UpdatePanel upCarSegments;
        
        /// <summary>
        /// ucCarSegmentParameters control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Mars.App.UserControls.Phase4.Administration.Mapping.EntityParameter ucCarSegmentParameters;
        
        /// <summary>
        /// ucCarSegmentGrid control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Mars.App.UserControls.Phase4.Administration.Mapping.EntityGrid ucCarSegmentGrid;
        
        /// <summary>
        /// ucCarSegmentPopup control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Mars.App.UserControls.Phase4.Administration.Mapping.EntityPopups.CarSegmentPopup ucCarSegmentPopup;
        
        /// <summary>
        /// upCarClasses control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.UpdatePanel upCarClasses;
        
        /// <summary>
        /// ucCarClassParamters control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Mars.App.UserControls.Phase4.Administration.Mapping.EntityParameter ucCarClassParamters;
        
        /// <summary>
        /// ucCarClassGrid control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Mars.App.UserControls.Phase4.Administration.Mapping.EntityGrid ucCarClassGrid;
        
        /// <summary>
        /// ucCarClassPopup control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Mars.App.UserControls.Phase4.Administration.Mapping.EntityPopups.CarClassPopup ucCarClassPopup;
        
        /// <summary>
        /// upCarGroups control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.UpdatePanel upCarGroups;
        
        /// <summary>
        /// ucCarGroupParameters control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Mars.App.UserControls.Phase4.Administration.Mapping.EntityParameter ucCarGroupParameters;
        
        /// <summary>
        /// ucCarGroupGrid control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Mars.App.UserControls.Phase4.Administration.Mapping.EntityGrid ucCarGroupGrid;
        
        /// <summary>
        /// ucCarGroupPopup control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Mars.App.UserControls.Phase4.Administration.Mapping.EntityPopups.CarGroupPopup ucCarGroupPopup;
    }
}
