//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Management.Mappings {
    
    
    public partial class Default {
        
        /// <summary>
        /// UpdatePanelMaintenanceMappingTable control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.UpdatePanel UpdatePanelMaintenanceMappingTable;
        
        /// <summary>
        /// UserControlPageInformation control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::App.UserControls.Pages.PageInformation UserControlPageInformation;
        
        /// <summary>
        /// MappingSelection control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::App.UserControls.Mappings.Common.MappingSelection MappingSelection;
        
        /// <summary>
        /// MappingCountryGridview control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::App.UserControls.Mappings.Gridviews.CountryGridview MappingCountryGridview;
        
        /// <summary>
        /// MappingAreaCodeGridview control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::App.UserControls.Mappings.Gridviews.AreaCodeGridview MappingAreaCodeGridview;
        
        /// <summary>
        /// MappingCMSPoolGridview control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::App.UserControls.Mappings.Gridviews.CMSPoolGridview MappingCMSPoolGridview;
        
        /// <summary>
        /// MappingCMSLocationGridview control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::App.UserControls.Mappings.Gridviews.CMSLocationGridview MappingCMSLocationGridview;
        
        /// <summary>
        /// MappingOPSRegionGridviews control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::App.UserControls.Mappings.Gridviews.OPSRegionGridview MappingOPSRegionGridviews;
        
        /// <summary>
        /// MappingOPSAreaGridview control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::App.UserControls.Mappings.Gridviews.OPSAreaGridview MappingOPSAreaGridview;
        
        /// <summary>
        /// MappingLocationGridview control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::App.UserControls.Mappings.Gridviews.LocationGridview MappingLocationGridview;
        
        /// <summary>
        /// MappingCarSegmentGridview control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::App.UserControls.Mappings.Gridviews.CarSegmentGridview MappingCarSegmentGridview;
        
        /// <summary>
        /// MappingCarClassGridview control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::App.UserControls.Mappings.Gridviews.CarClassGridview MappingCarClassGridview;
        
        /// <summary>
        /// MappingCarGroupGridview control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::App.UserControls.Mappings.Gridviews.CarGroupGridview MappingCarGroupGridview;
        
        /// <summary>
        /// MappingModelCodesGridview control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::App.UserControls.Mappings.Gridviews.ModelCodeGridview MappingModelCodesGridview;
        
        /// <summary>
        /// DeleteConfirm control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::App.UserControls.Confirm.DeleteConfirm DeleteConfirm;
    }
}
