CREATE TABLE [General].[Fact_NonRevLog_Summary] (
    [log_id]                 INT           IDENTITY (1, 1) NOT NULL,
    [dim_calendar_id]        INT           NULL,
    [country_car]            VARCHAR (10)  NULL,
    [country_loc]            VARCHAR (10)  NULL,
    [location_group]         VARCHAR (100) NULL,
    [location_group_id]      INT           NULL,
    [location_pool]          VARCHAR (100) NULL,
    [location_pool_id]       INT           NULL,
    [location_ops_area]      VARCHAR (100) NULL,
    [location_ops_area_id]   INT           NULL,
    [location_ops_region]    VARCHAR (100) NULL,
    [location_ops_region_id] INT           NULL,
    [car_group]              VARCHAR (20)  NULL,
    [car_group_id]           INT           NULL,
    [car_class]              VARCHAR (100) NULL,
    [car_class_id]           INT           NULL,
    [car_segment]            VARCHAR (100) NULL,
    [car_segment_id]         INT           NULL,
    [location]               VARCHAR (100) NULL,
    [total_records]          INT           NULL,
    [total_fleet]            INT           NULL,
    [operational_fleet]      INT           NULL,
    [available_fleet]        INT           NULL,
    [rev_fleet]              INT           NULL,
    [non_rev_fleet]          INT           NULL,
    [daygroup1]              INT           NULL,
    [daygroup2]              INT           NULL,
    [daygroup3]              INT           NULL,
    [daygroup4]              INT           NULL,
    [daygroup5]              INT           NULL,
    [daygroup6]              INT           NULL,
    [daygroup7]              INT           NULL,
    [daygroup8]              INT           NULL,
    [daygroup9]              INT           NULL,
    [total_fleet_cs]         INT           NULL,
    [operational_fleet_cs]   INT           NULL,
    [available_fleet_cs]     INT           NULL,
    [rev_fleet_cs]           INT           NULL,
    [non_rev_fleet_cs]       INT           NULL,
    [daygroup1_cs]           INT           NULL,
    [daygroup2_cs]           INT           NULL,
    [daygroup3_cs]           INT           NULL,
    [daygroup4_cs]           INT           NULL,
    [daygroup5_cs]           INT           NULL,
    [daygroup6_cs]           INT           NULL,
    [daygroup7_cs]           INT           NULL,
    [daygroup8_cs]           INT           NULL,
    [daygroup9_cs]           INT           NULL,
    [total_fleet_lc]         INT           NULL,
    [operational_fleet_lc]   INT           NULL,
    [available_fleet_lc]     INT           NULL,
    [rev_fleet_lc]           INT           NULL,
    [non_rev_fleet_lc]       INT           NULL,
    [daygroup1_lc]           INT           NULL,
    [daygroup2_lc]           INT           NULL,
    [daygroup3_lc]           INT           NULL,
    [daygroup4_lc]           INT           NULL,
    [daygroup5_lc]           INT           NULL,
    [daygroup6_lc]           INT           NULL,
    [daygroup7_lc]           INT           NULL,
    [daygroup8_lc]           INT           NULL,
    [daygroup9_lc]           INT           NULL,
    [total_fleet_ad]         INT           NULL,
    [operational_fleet_ad]   INT           NULL,
    [available_fleet_ad]     INT           NULL,
    [rev_fleet_ad]           INT           NULL,
    [non_rev_fleet_ad]       INT           NULL,
    [daygroup1_ad]           INT           NULL,
    [daygroup2_ad]           INT           NULL,
    [daygroup3_ad]           INT           NULL,
    [daygroup4_ad]           INT           NULL,
    [daygroup5_ad]           INT           NULL,
    [daygroup6_ad]           INT           NULL,
    [daygroup7_ad]           INT           NULL,
    [daygroup8_ad]           INT           NULL,
    [daygroup9_ad]           INT           NULL,
    [total_fleet_hd]         INT           NULL,
    [operational_fleet_hd]   INT           NULL,
    [available_fleet_hd]     INT           NULL,
    [rev_fleet_hd]           INT           NULL,
    [non_rev_fleet_hd]       INT           NULL,
    [daygroup1_hd]           INT           NULL,
    [daygroup2_hd]           INT           NULL,
    [daygroup3_hd]           INT           NULL,
    [daygroup4_hd]           INT           NULL,
    [daygroup5_hd]           INT           NULL,
    [daygroup6_hd]           INT           NULL,
    [daygroup7_hd]           INT           NULL,
    [daygroup8_hd]           INT           NULL,
    [daygroup9_hd]           INT           NULL,
    [total_fleet_op]         INT           NULL,
    [operational_fleet_op]   INT           NULL,
    [available_fleet_op]     INT           NULL,
    [rev_fleet_op]           INT           NULL,
    [non_rev_fleet_op]       INT           NULL,
    [daygroup1_op]           INT           NULL,
    [daygroup2_op]           INT           NULL,
    [daygroup3_op]           INT           NULL,
    [daygroup4_op]           INT           NULL,
    [daygroup5_op]           INT           NULL,
    [daygroup6_op]           INT           NULL,
    [daygroup7_op]           INT           NULL,
    [daygroup8_op]           INT           NULL,
    [daygroup9_op]           INT           NULL,
    [total_fleet_tt]         INT           NULL,
    [operational_fleet_tt]   INT           NULL,
    [available_fleet_tt]     INT           NULL,
    [rev_fleet_tt]           INT           NULL,
    [non_rev_fleet_tt]       INT           NULL,
    [daygroup1_tt]           INT           NULL,
    [daygroup2_tt]           INT           NULL,
    [daygroup3_tt]           INT           NULL,
    [daygroup4_tt]           INT           NULL,
    [daygroup5_tt]           INT           NULL,
    [daygroup6_tt]           INT           NULL,
    [daygroup7_tt]           INT           NULL,
    [daygroup8_tt]           INT           NULL,
    [daygroup9_tt]           INT           NULL,
    [OperationalStatusCode]  VARCHAR (20)  NULL,
    [Rep_DayOfWeek]          INT           NULL,
    PRIMARY KEY CLUSTERED ([log_id] ASC)
);


GO
CREATE NONCLUSTERED INDEX [CalId_Index]
    ON [General].[Fact_NonRevLog_Summary]([dim_calendar_id] ASC);

