CREATE TABLE [General].[Staging_Fleet] (
    [Serial]            VARCHAR (50)  NULL,
    [Plate]             VARCHAR (50)  NULL,
    [Unit]              VARCHAR (50)  NULL,
    [Country]           VARCHAR (10)  NULL,
    [MSODate]           DATETIME      NULL,
    [Model]             VARCHAR (20)  NULL,
    [ModelDesc]         VARCHAR (255) NULL,
    [Color]             VARCHAR (10)  NULL,
    [CarGroup]          VARCHAR (20)  NULL,
    [OwnArea]           VARCHAR (50)  NULL,
    [LastDailyFileDate] DATETIME      NULL,
    [NRdays]            INT           NULL,
    [BDDays]            INT           NULL,
    [MMDays]            INT           NULL,
    [Lstwwd]            VARCHAR (50)  NULL,
    [LstNo]             VARCHAR (20)  NULL,
    [LstDate]           DATETIME      NULL,
    [Duewwd]            VARCHAR (50)  NULL,
    [DueDate]           DATETIME      NULL,
    [Prevwwd]           VARCHAR (50)  NULL,
    [LstMlg]            FLOAT (53)    NULL,
    [DrvName]           VARCHAR (255) NULL,
    [OperStat]          VARCHAR (5)   NULL,
    [MoveType]          VARCHAR (5)   NULL,
    [DepStat]           VARCHAR (5)   NULL,
    [CarHold]           VARCHAR (5)   NULL,
    [IDate]             DATETIME      NULL,
    [IsActive]          BIT           NULL,
    [IsOpen]            BIT           NULL,
    [NonRevLogId]       INT           NULL,
    [VehicleId]         INT           NULL,
    [Fleet_rac_ops]     BIT           NULL,
    [Fleet_rac_ttl]     BIT           NULL,
    [Fleet_carsales]    BIT           NULL,
    [Fleet_licensee]    BIT           NULL,
    [Fleet_adv]         BIT           NULL,
    [Fleet_hod]         BIT           NULL,
    [TotalFleet]        INT           NULL,
    [AvailableFleet]    INT           NULL,
    [OperationalFleet]  INT           NULL,
    [DayGroupCode]      VARCHAR (10)  NULL,
    [SDate]             DATETIME      NULL
);

