//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.AvailabilityTool.HistoricalTrend {
    
    
    public partial class Default {
        
        /// <summary>
        /// UpdatePanelHistoricalTrend control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.UpdatePanel UpdatePanelHistoricalTrend;
        
        /// <summary>
        /// UserControlPageInformation control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::App.UserControls.Pages.PageInformation UserControlPageInformation;
        
        /// <summary>
        /// UserControlReportSelections control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::App.UserControls.Reports.ReportSelections UserControlReportSelections;
        
        /// <summary>
        /// EmptyDataTemplateHistoricalTrend control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::App.UserControls.EmptyData.EmptyDataTemplate EmptyDataTemplateHistoricalTrend;
        
        /// <summary>
        /// AvailibilityChartHistoricalTrend control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::App.UserControls.Charts.AvailabilityChart AvailibilityChartHistoricalTrend;
        
        /// <summary>
        /// UserControlReportSettings control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::App.UserControls.Reports.ReportSettings UserControlReportSettings;
        
        /// <summary>
        /// ModalConfirmHistoricalTrend control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::App.UserControls.Confirm.ModalConfirm ModalConfirmHistoricalTrend;
        
        /// <summary>
        /// upChartProgress control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.UpdateProgress upChartProgress;
    }
}
