//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mars.FleetAllocation.UserControls.AdditionsLimits {
    
    
    public partial class MonthlyAdditionsLimits {
        
        /// <summary>
        /// ucMonthlyAdds control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Mars.FleetAllocation.UserControls.AutoGrid ucMonthlyAdds;
        
        /// <summary>
        /// MonthlyLimitDetails control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Mars.FleetAllocation.UserControls.DistributionLimits.MonthlyLimitDetails MonthlyLimitDetails;
        
        /// <summary>
        /// WeeklyLimitDetails control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Mars.FleetAllocation.UserControls.DistributionLimits.WeeklyLimitDetails WeeklyLimitDetails;
    }
}
