//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.AvailabilityTool.KPIDownload {
    
    
    public partial class Default {
        
        /// <summary>
        /// UpdatePanelKPIDownload control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.UpdatePanel UpdatePanelKPIDownload;
        
        /// <summary>
        /// UserControlPageInformation control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::App.UserControls.Pages.PageInformation UserControlPageInformation;
        
        /// <summary>
        /// UserControlReportSelections control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::App.UserControls.Reports.ReportSelections UserControlReportSelections;
        
        /// <summary>
        /// AvailabilityChartKPIDownloadVehicleStatus control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::App.UserControls.Charts.AvailabilityChart AvailabilityChartKPIDownloadVehicleStatus;
        
        /// <summary>
        /// AvailabilityChartKPIDownloadIdleUnitsOnPeak control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::App.UserControls.Charts.AvailabilityChart AvailabilityChartKPIDownloadIdleUnitsOnPeak;
        
        /// <summary>
        /// AvailabilityChartKPIDownloadOperationalUtilization control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::App.UserControls.Charts.AvailabilityChart AvailabilityChartKPIDownloadOperationalUtilization;
        
        /// <summary>
        /// UserControlReportSettings control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::App.UserControls.Reports.ReportSettings UserControlReportSettings;
        
        /// <summary>
        /// ModalConfirmKPIDownload control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::App.UserControls.Confirm.ModalConfirm ModalConfirmKPIDownload;
        
        /// <summary>
        /// upChartProgress control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.UpdateProgress upChartProgress;
    }
}
