CREATE TABLE [Inp].[Fact_FLEET_EUROPE_SUMMARY_HISTORY] (
    [dim_Calendar_id]                INT          NOT NULL,
    [COUNTRY]                        VARCHAR (10) NOT NULL,
    [dim_Location_id]                INT          NOT NULL,
    [car_group]                      VARCHAR (10) NULL,
    [FLEET_CARSALES]                 BIT          NOT NULL,
    [FLEET_RAC_TTL]                  BIT          NOT NULL,
    [FLEET_RAC_OPS]                  BIT          NOT NULL,
    [FLEET_LICENSEE]                 BIT          NOT NULL,
    [TOTAL_FLEET]                    INT          NOT NULL,
    [CARSALES]                       INT          NOT NULL,
    [CARHOLD_H]                      INT          NOT NULL,
    [CARHOLD_L]                      INT          NOT NULL,
    [CU]                             INT          NOT NULL,
    [HA]                             INT          NOT NULL,
    [HL]                             INT          NOT NULL,
    [LL]                             INT          NOT NULL,
    [NC]                             INT          NOT NULL,
    [PL]                             INT          NOT NULL,
    [TC]                             INT          NOT NULL,
    [SV]                             INT          NOT NULL,
    [WS]                             INT          NOT NULL,
    [WS_NONRAC]                      INT          NOT NULL,
    [OPERATIONAL_FLEET]              INT          NOT NULL,
    [BD]                             INT          NOT NULL,
    [MM]                             INT          NOT NULL,
    [TW]                             INT          NOT NULL,
    [TB]                             INT          NOT NULL,
    [WS_RAC]                         INT          NOT NULL,
    [AVAILABLE_TB]                   INT          NOT NULL,
    [FS]                             INT          NOT NULL,
    [RL]                             INT          NOT NULL,
    [RP]                             INT          NOT NULL,
    [TN]                             INT          NOT NULL,
    [AVAILABLE_FLEET]                INT          NOT NULL,
    [RT]                             INT          NOT NULL,
    [SU]                             INT          NOT NULL,
    [GOLD]                           INT          NOT NULL,
    [PREDELIVERY]                    INT          NOT NULL,
    [OVERDUE]                        INT          NOT NULL,
    [ON_RENT]                        INT          NOT NULL,
    [TOTAL_FLEET_MIN]                INT          NULL,
    [CARSALES_MIN]                   INT          NULL,
    [CARHOLD_H_MIN]                  INT          NULL,
    [CARHOLD_L_MIN]                  INT          NULL,
    [CU_MIN]                         INT          NOT NULL,
    [HA_MIN]                         INT          NOT NULL,
    [HL_MIN]                         INT          NOT NULL,
    [LL_MIN]                         INT          NOT NULL,
    [NC_MIN]                         INT          NOT NULL,
    [PL_MIN]                         INT          NOT NULL,
    [TC_MIN]                         INT          NOT NULL,
    [SV_MIN]                         INT          NOT NULL,
    [WS_MIN]                         INT          NOT NULL,
    [WS_NONRAC_MIN]                  INT          NOT NULL,
    [OPERATIONAL_FLEET_MIN]          INT          NOT NULL,
    [BD_MIN]                         INT          NOT NULL,
    [MM_MIN]                         INT          NOT NULL,
    [TW_MIN]                         INT          NOT NULL,
    [TB_MIN]                         INT          NOT NULL,
    [WS_RAC_MIN]                     INT          NOT NULL,
    [AVAILABLE_TB_MIN]               INT          NOT NULL,
    [FS_MIN]                         INT          NOT NULL,
    [RL_MIN]                         INT          NOT NULL,
    [RP_MIN]                         INT          NOT NULL,
    [TN_MIN]                         INT          NOT NULL,
    [AVAILABLE_FLEET_MIN]            INT          NOT NULL,
    [RT_MIN]                         INT          NOT NULL,
    [SU_MIN]                         INT          NOT NULL,
    [GOLD_MIN]                       INT          NOT NULL,
    [PREDELIVERY_MIN]                INT          NOT NULL,
    [OVERDUE_MIN]                    INT          NOT NULL,
    [ON_RENT_MIN]                    INT          NOT NULL,
    [TOTAL_FLEET_MAX]                INT          NULL,
    [CARSALES_MAX]                   INT          NOT NULL,
    [CARHOLD_H_MAX]                  INT          NOT NULL,
    [CARHOLD_L_MAX]                  INT          NOT NULL,
    [CU_MAX]                         INT          NOT NULL,
    [HA_MAX]                         INT          NOT NULL,
    [HL_MAX]                         INT          NOT NULL,
    [LL_MAX]                         INT          NOT NULL,
    [NC_MAX]                         INT          NOT NULL,
    [PL_MAX]                         INT          NOT NULL,
    [TC_MAX]                         INT          NOT NULL,
    [SV_MAX]                         INT          NOT NULL,
    [WS_MAX]                         INT          NOT NULL,
    [WS_NONRAC_MAX]                  INT          NOT NULL,
    [OPERATIONAL_FLEET_MAX]          INT          NOT NULL,
    [BD_MAX]                         INT          NOT NULL,
    [MM_MAX]                         INT          NOT NULL,
    [TW_MAX]                         INT          NOT NULL,
    [TB_MAX]                         INT          NOT NULL,
    [WS_RAC_MAX]                     INT          NOT NULL,
    [AVAILABLE_TB_MAX]               INT          NOT NULL,
    [FS_MAX]                         INT          NOT NULL,
    [RL_MAX]                         INT          NOT NULL,
    [RP_MAX]                         INT          NOT NULL,
    [TN_MAX]                         INT          NOT NULL,
    [AVAILABLE_FLEET_MAX]            INT          NOT NULL,
    [RT_MAX]                         INT          NOT NULL,
    [SU_MAX]                         INT          NOT NULL,
    [GOLD_MAX]                       INT          NOT NULL,
    [PREDELIVERY_MAX]                INT          NOT NULL,
    [OVERDUE_MAX]                    INT          NOT NULL,
    [ON_RENT_MAX]                    INT          NOT NULL,
    [TOTAL_FLEET_MAX_ABSOLUTE]       INT          NOT NULL,
    [OPERATIONAL_FLEET_MAX_ABSOLUTE] INT          NOT NULL,
    [OVERDUE_MAX_ABSOLUTE]           INT          NOT NULL,
    [ON_RENT_MAX_ABSOLUTE]           INT          NOT NULL,
    [FLEET_ADV]                      BIT          NULL,
    [FLEET_HOD]                      BIT          NULL
);


GO
CREATE NONCLUSTERED INDEX [ix_Fact_FLEET_EUROPE_SUMMARY_HISTORY_01]
    ON [Inp].[Fact_FLEET_EUROPE_SUMMARY_HISTORY]([COUNTRY] ASC);


GO
CREATE CLUSTERED INDEX [ix_Fact_FLEET_EUROPE_SUMMARY_HISTORY]
    ON [Inp].[Fact_FLEET_EUROPE_SUMMARY_HISTORY]([dim_Calendar_id] ASC);

