CREATE TABLE [Inp].[Fact_FLEET_EUROPE_SUMMARY_HISTORY_WeekOfYear] (
    [dim_Calendar_id]         INT          NOT NULL,
    [Rep_Year]                INT          NULL,
    [WeekOfYear]              INT          NULL,
    [NumDays]                 INT          NOT NULL,
    [COUNTRY]                 VARCHAR (10) NOT NULL,
    [car_group]               VARCHAR (10) NULL,
    [dim_Location_id]         INT          NOT NULL,
    [FLEET_CARSALES]          BIT          NOT NULL,
    [FLEET_RAC_TTL]           BIT          NOT NULL,
    [FLEET_RAC_OPS]           BIT          NOT NULL,
    [FLEET_LICENSEE]          BIT          NOT NULL,
    [TOTAL_FLEET]             INT          NOT NULL,
    [CARSALES]                INT          NOT NULL,
    [CARHOLD_H]               INT          NOT NULL,
    [CARHOLD_L]               INT          NOT NULL,
    [CU]                      INT          NOT NULL,
    [HA]                      INT          NOT NULL,
    [HL]                      INT          NOT NULL,
    [LL]                      INT          NOT NULL,
    [NC]                      INT          NOT NULL,
    [PL]                      INT          NOT NULL,
    [TC]                      INT          NOT NULL,
    [SV]                      INT          NOT NULL,
    [WS]                      INT          NOT NULL,
    [WS_NONRAC]               INT          NOT NULL,
    [OPERATIONAL_FLEET]       INT          NOT NULL,
    [BD]                      INT          NOT NULL,
    [MM]                      INT          NOT NULL,
    [TW]                      INT          NOT NULL,
    [TB]                      INT          NOT NULL,
    [WS_RAC]                  INT          NOT NULL,
    [AVAILABLE_TB]            INT          NOT NULL,
    [FS]                      INT          NOT NULL,
    [RL]                      INT          NOT NULL,
    [RP]                      INT          NOT NULL,
    [TN]                      INT          NOT NULL,
    [AVAILABLE_FLEET]         INT          NOT NULL,
    [RT]                      INT          NOT NULL,
    [SU]                      INT          NOT NULL,
    [GOLD]                    INT          NOT NULL,
    [PREDELIVERY]             INT          NOT NULL,
    [OVERDUE]                 INT          NOT NULL,
    [ON_RENT]                 INT          NOT NULL,
    [RT_MIN_SUM]              INT          DEFAULT ((0)) NOT NULL,
    [AVAILABLE_FLEET_MIN_SUM] INT          DEFAULT ((0)) NOT NULL,
    [RT_MAX_SUM]              INT          DEFAULT ((0)) NOT NULL,
    [AVAILABLE_FLEET_MAX_SUM] INT          DEFAULT ((0)) NOT NULL,
    [FLEET_ADV]               BIT          NULL,
    [FLEET_HOD]               BIT          NULL
);


GO
CREATE CLUSTERED INDEX [ix_Fact_FLEET_EUROPE_SUMMARY_HISTORY_WeekOfYear]
    ON [Inp].[Fact_FLEET_EUROPE_SUMMARY_HISTORY_WeekOfYear]([dim_Calendar_id] ASC);

