//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mars.FleetAllocation.UserControls.Reports {
    
    
    public partial class SiteComparison {
        
        /// <summary>
        /// ucSiteComparisonChart control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Mars.FleetAllocation.UserControls.Reports.SiteComparisonChart ucSiteComparisonChart;
        
        /// <summary>
        /// agSiteComparison control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Mars.FleetAllocation.UserControls.AutoGrid agSiteComparison;
    }
}
