-- =============================================
-- Author:		Javier
-- Create date: October 2012
-- Description:	
-- =============================================
CREATE PROCEDURE [Export].[TransferDesk_Fleet]

AS
BEGIN

	SET NOCOUNT ON;

	SELECT  
		CONVERT(VARCHAR(2),LTRIM(RTRIM(OWNCTRY))) + ';' + 
		CONVERT(VARCHAR(2),LTRIM(RTRIM(LSTCTRY))) + ';' + 
		CONVERT(VARCHAR(7),LTRIM(RTRIM(LSTWWD)))  + ';' +
		CASE WHEN LEN(VC) = 1 THEN  CONVERT(VARCHAR(1),LTRIM(RTRIM(VC))) ELSE CONVERT(VARCHAR(2),LTRIM(RTRIM(VC))) END 
		+ ';' +
		CONVERT(VARCHAR(7),LTRIM(RTRIM(UNIT)))     + ';' +

		CASE	WHEN LEN(LICENSE) = 5 THEN CONVERT(VARCHAR(5),LTRIM(RTRIM(LICENSE)))
				WHEN LEN(LICENSE) = 6 THEN CONVERT(VARCHAR(6),LTRIM(RTRIM(LICENSE)))
				WHEN LEN(LICENSE) = 7 THEN CONVERT(VARCHAR(7),LTRIM(RTRIM(LICENSE)))
				WHEN LEN(LICENSE) = 8 THEN CONVERT(VARCHAR(8),LTRIM(RTRIM(LICENSE)))
				WHEN LEN(LICENSE) = 9 THEN CONVERT(VARCHAR(9),LTRIM(RTRIM(LICENSE))) END
		+ ';' +
		CONVERT(VARCHAR(4),LTRIM(RTRIM(MODEL))) + ';' +
		CASE	WHEN LEN(MODDESC) = 1  THEN CONVERT(VARCHAR(1),LTRIM(RTRIM(MODDESC)))
				WHEN LEN(MODDESC) = 2  THEN CONVERT(VARCHAR(2),LTRIM(RTRIM(MODDESC)))
				WHEN LEN(MODDESC) = 3  THEN CONVERT(VARCHAR(3),LTRIM(RTRIM(MODDESC)))
				WHEN LEN(MODDESC) = 4  THEN CONVERT(VARCHAR(4),LTRIM(RTRIM(MODDESC)))
				WHEN LEN(MODDESC) = 5  THEN CONVERT(VARCHAR(5),LTRIM(RTRIM(MODDESC)))
				WHEN LEN(MODDESC) = 6  THEN CONVERT(VARCHAR(6),LTRIM(RTRIM(MODDESC)))
				WHEN LEN(MODDESC) = 7  THEN CONVERT(VARCHAR(7),LTRIM(RTRIM(MODDESC)))
				WHEN LEN(MODDESC) = 8  THEN CONVERT(VARCHAR(8),LTRIM(RTRIM(MODDESC)))
				WHEN LEN(MODDESC) = 9  THEN CONVERT(VARCHAR(9),LTRIM(RTRIM(MODDESC)))
				WHEN LEN(MODDESC) = 10 THEN CONVERT(VARCHAR(10),LTRIM(RTRIM(MODDESC)))
				WHEN LEN(MODDESC) = 11 THEN CONVERT(VARCHAR(11),LTRIM(RTRIM(MODDESC)))
				WHEN LEN(MODDESC) = 12 THEN CONVERT(VARCHAR(12),LTRIM(RTRIM(MODDESC)))
				WHEN LEN(MODDESC) = 13 THEN CONVERT(VARCHAR(13),LTRIM(RTRIM(MODDESC)))
				WHEN LEN(MODDESC) = 14 THEN CONVERT(VARCHAR(14),LTRIM(RTRIM(MODDESC)))
				WHEN LEN(MODDESC) = 15 THEN CONVERT(VARCHAR(15),LTRIM(RTRIM(MODDESC)))
				WHEN LEN(MODDESC) = 16 THEN CONVERT(VARCHAR(16),LTRIM(RTRIM(MODDESC)))
				WHEN LEN(MODDESC) = 17 THEN CONVERT(VARCHAR(17),LTRIM(RTRIM(MODDESC)))
				WHEN LEN(MODDESC) = 18 THEN CONVERT(VARCHAR(18),LTRIM(RTRIM(MODDESC)))
				WHEN LEN(MODDESC) = 19 THEN CONVERT(VARCHAR(19),LTRIM(RTRIM(MODDESC)))
				WHEN LEN(MODDESC) = 20 THEN CONVERT(VARCHAR(20),LTRIM(RTRIM(MODDESC))) END
		+ ';' +
		CONVERT(VARCHAR(3),LTRIM(RTRIM(MOVETYPE)))
	FROM qry_TransferDesk
	ORDER BY OWNCTRY , LSTCTRY


END