//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mars.FleetAllocation.UserControls {
    
    
    public partial class DemandGapDisplay {
        
        /// <summary>
        /// upnlDemandGap control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.UpdatePanel upnlDemandGap;
        
        /// <summary>
        /// ucParameters control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Mars.FleetAllocation.UserControls.FaoParameter ucParameters;
        
        /// <summary>
        /// btnCaluclate control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button btnCaluclate;
        
        /// <summary>
        /// hfLoading control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField hfLoading;
        
        /// <summary>
        /// ucUpdateProgress control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Mars.App.UserControls.Phase4.Common.UpdateProgress ucUpdateProgress;
        
        /// <summary>
        /// pnlGapFill control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel pnlGapFill;
        
        /// <summary>
        /// ucDemanGapStageOneGrid control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Mars.FleetAllocation.UserControls.AutoGrid ucDemanGapStageOneGrid;
        
        /// <summary>
        /// ucDgVis control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Mars.FleetAllocation.UserControls.AutoGrid ucDgVis;
        
        /// <summary>
        /// ucMonthlyLimit control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Mars.FleetAllocation.UserControls.DistributionLimits.MonthlyLimitDetails ucMonthlyLimit;
        
        /// <summary>
        /// ucWeeklyLimit control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Mars.FleetAllocation.UserControls.DistributionLimits.WeeklyLimitDetails ucWeeklyLimit;
        
        /// <summary>
        /// ucResult control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Mars.FleetAllocation.UserControls.AutoGrid ucResult;
        
        /// <summary>
        /// tbSummary control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox tbSummary;
    }
}
