CREATE TABLE [Export].[GermanyForecast] (
    [Repdate]            DATETIME       NULL,
    [Country]            VARCHAR (10)   NULL,
    [CmsLocationGroupId] INT            NULL,
    [CmsLocationGroup]   VARCHAR (20)   NULL,
    [CmsPool]            VARCHAR (10)   NULL,
    [CarClassId]         INT            NULL,
    [CarClass]           VARCHAR (10)   NULL,
    [Constrained]        INT            CONSTRAINT [DF_GermanyForecast_Constrained] DEFAULT ((0)) NULL,
    [Unconstrained]      INT            CONSTRAINT [DF_GermanyForecast_Unconstrained] DEFAULT ((0)) NULL,
    [FleetForecast]      INT            CONSTRAINT [DF_GermanyForecast_Fleet] DEFAULT ((0)) NULL,
    [ReservationsBooked] INT            CONSTRAINT [DF_GermanyForecast_ReservationsBooked] DEFAULT ((0)) NULL,
    [CurrentOnRent]      INT            CONSTRAINT [DF_GermanyForecast_CurrentOnRent] DEFAULT ((0)) NULL,
    [OnRentLy]           INT            CONSTRAINT [DF_GermanyForecast_OnRentLy] DEFAULT ((0)) NULL,
    [AvailableFleet]     INT            CONSTRAINT [DF_GermanyForecast_AvailableFleet] DEFAULT ((0)) NULL,
    [AdjustmentBu1]      INT            CONSTRAINT [DF_GermanyForecast_AdjustmentBu1] DEFAULT ((0)) NULL,
    [AdjustmentBu2]      INT            CONSTRAINT [DF_GermanyForecast_AdjustmentBu2] DEFAULT ((0)) NULL,
    [AdjustmentRc]       INT            CONSTRAINT [DF_GermanyForecast_AdjustmentRc] DEFAULT ((0)) NULL,
    [AdjustmentTd]       DECIMAL (6, 2) NULL,
    [TotalFleet]         INT            CONSTRAINT [DF_GermanyForecast_TotalFleet] DEFAULT ((0)) NULL,
    [Additions]          INT            CONSTRAINT [DF_GermanyForecast_Additions] DEFAULT ((0)) NULL,
    [Deletions]          INT            CONSTRAINT [DF_GermanyForecast_Deletions] DEFAULT ((0)) NULL,
    [Amount]             INT            CONSTRAINT [DF_GermanyForecast_Amount] DEFAULT ((0)) NULL,
    [NonRev7]            INT            CONSTRAINT [DF_GermanyForecast_NonRev7] DEFAULT ((0)) NULL,
    [OnRentMax]          INT            CONSTRAINT [DF_GermanyForecast_OnRentMax] DEFAULT ((0)) NULL,
    [OnRentAvg]          INT            CONSTRAINT [DF_GermanyForecast_OnRentAvg] DEFAULT ((0)) NULL,
    [OnRent]             INT            CONSTRAINT [DF_GermanyForecast_OnRent] DEFAULT ((0)) NULL,
    [Maintenance]        INT            CONSTRAINT [DF_GermanyForecast_Maintenance] DEFAULT ((0)) NULL,
    [MaintenanceMax]     INT            CONSTRAINT [DF_GermanyForecast_MaintenanceMax] DEFAULT ((0)) NULL,
    [Unavailable]        INT            CONSTRAINT [DF_GermanyForecast_Unavailable] DEFAULT ((0)) NULL,
    [UnavailableMax]     INT            CONSTRAINT [DF_GermanyForecast_UnavailableMax] DEFAULT ((0)) NULL,
    [ServiceUnits]       INT            CONSTRAINT [DF_GermanyForecast_ServiceUnits] DEFAULT ((0)) NULL,
    [ServiceUnitsMax]    INT            CONSTRAINT [DF_GermanyForecast_ServiceUnitsMax] DEFAULT ((0)) NULL,
    [Overdue]            INT            CONSTRAINT [DF_GermanyForecast_Overdue] DEFAULT ((0)) NULL,
    [OverdueMax]         INT            CONSTRAINT [DF_GermanyForecast_OverdueMax] DEFAULT ((0)) NULL,
    [CarSales]           INT            CONSTRAINT [DF_GermanyForecast_CarSales] DEFAULT ((0)) NULL,
    [CarSalesMax]        INT            CONSTRAINT [DF_GermanyForecast_CarSalesMax] DEFAULT ((0)) NULL,
    [Turnback]           INT            CONSTRAINT [DF_GermanyForecast_Turnback] DEFAULT ((0)) NULL,
    [TurnbackMax]        INT            CONSTRAINT [DF_GermanyForecast_TurnbackMax] DEFAULT ((0)) NULL,
    [RtMax]              INT            CONSTRAINT [DF_GermanyForecast_RtMax] DEFAULT ((0)) NULL,
    [Rt]                 INT            CONSTRAINT [DF_GermanyForecast_Rt] DEFAULT ((0)) NULL,
    [OpFleet]            INT            CONSTRAINT [DF_GermanyForecast_OpFleet] DEFAULT ((0)) NULL,
    [OpFleetMax]         INT            CONSTRAINT [DF_GermanyForecast_OpFleetMax] DEFAULT ((0)) NULL,
    [OpFleetCalc]        INT            CONSTRAINT [DF_GermanyForecast_OpFleetCalc] DEFAULT ((0)) NULL,
    [ExpectedFleet]      INT            CONSTRAINT [DF_GermanyForecast_ExpectedFleet] DEFAULT ((0)) NULL
);





