CREATE TABLE [dbo].[FleetNow] (
    [FleetNowId]  INT        IDENTITY (1, 1) NOT NULL,
    [Timestamp]   DATETIME   NOT NULL,
    [CarGroupId]  INT        NOT NULL,
    [LocationId]  INT        NOT NULL,
    [FleetTypeId] TINYINT    NOT NULL,
    [SumTotal]    INT        NOT NULL,
    [SumBd]       INT        NOT NULL,
    [SumCu]       INT        NOT NULL,
    [SumFs]       INT        NOT NULL,
    [SumHa]       INT        NOT NULL,
    [SumHl]       INT        NOT NULL,
    [SumLl]       INT        NOT NULL,
    [SumMm]       INT        NOT NULL,
    [SumNc]       INT        NOT NULL,
    [SumPl]       INT        NOT NULL,
    [SumRl]       INT        NOT NULL,
    [SumRp]       INT        NOT NULL,
    [SumIdle]     INT        NOT NULL,
    [SumSu]       INT        NOT NULL,
    [SumSv]       INT        NOT NULL,
    [SumTb]       INT        NOT NULL,
    [SumTc]       INT        NOT NULL,
    [SumTn]       INT        NOT NULL,
    [SumTw]       INT        NOT NULL,
    [SumWs]       INT        NOT NULL,
    [SumOverdue]  INT        NOT NULL,
    [Utilization] FLOAT (53) NOT NULL,
    CONSTRAINT [PK_FleetNow] PRIMARY KEY CLUSTERED ([FleetNowId] ASC),
    CONSTRAINT [FK_FleetNow_CAR_GROUPS] FOREIGN KEY ([CarGroupId]) REFERENCES [dbo].[CAR_GROUPS] ([car_group_id]),
    CONSTRAINT [FK_FleetNow_LOCATIONS] FOREIGN KEY ([LocationId]) REFERENCES [dbo].[LOCATIONS] ([dim_Location_id]),
    CONSTRAINT [FK_FleetNow_VehicleFleetType] FOREIGN KEY ([FleetTypeId]) REFERENCES [dbo].[VehicleFleetType] ([VehicleFleetTypeId])
);

