CREATE TABLE [dbo].[VEHICLE_REMARKS] (
    [SERIAL]                 VARCHAR (25)  NOT NULL,
    [REMARK]                 VARCHAR (500) NULL,
    [EXPECTEDRESOLUTIONDATE] DATETIME      NULL,
    CONSTRAINT [PK_VEHICLE_REMARKS] PRIMARY KEY CLUSTERED ([SERIAL] ASC)
);

