//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarsPortal {
    
    
    public partial class Default {
        
        /// <summary>
        /// Communications control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Mars.App.UserControls.Panel.CommunicationsPanel Communications;
        
        /// <summary>
        /// Master property.
        /// </summary>
        /// <remarks>
        /// Auto-generated property.
        /// </remarks>
        public new App.MasterPages.Application Master {
            get {
                return ((App.MasterPages.Application)(base.Master));
            }
        }
    }
}
