CREATE TABLE [VehiclesAbroad].[CARS_ABROAD_HISTORY] (
    [REP_DATE]    DATETIME     NOT NULL,
    [COUNTRY_OWN] VARCHAR (10) NOT NULL,
    [COUNTRY_IN]  VARCHAR (10) NOT NULL,
    [COUNTRY_DUE] VARCHAR (10) NOT NULL,
    [TOTAL_FLEET] FLOAT (53)   NULL,
    [OTHER]       FLOAT (53)   NULL,
    [SHOP]        FLOAT (53)   NULL,
    [IDLE]        FLOAT (53)   NULL,
    [OVERDUE]     FLOAT (53)   NULL,
    [ON_RENT]     FLOAT (53)   NULL,
    CONSTRAINT [PK_CARS_ABROAD_HISTORY] PRIMARY KEY CLUSTERED ([REP_DATE] ASC, [COUNTRY_OWN] ASC, [COUNTRY_IN] ASC, [COUNTRY_DUE] ASC)
);

