CREATE TABLE [dbo].[MARS_CMS_NECESSARY_FLEET] (
    [COUNTRY]               VARCHAR (10)   NULL,
    [CMS_LOCATION_GROUP_ID] INT            NULL,
    [CAR_CLASS_ID]          INT            NULL,
    [UTILISATION]           NUMERIC (5, 2) NULL,
    [NONREV_FLEET]          NUMERIC (5, 2) NULL,
    [MarsCmsNessaryFleetId] INT            IDENTITY (1, 1) NOT NULL,
    CONSTRAINT [PK_MARS_CMS_NECESSARY_FLEET] PRIMARY KEY CLUSTERED ([MarsCmsNessaryFleetId] ASC),
    CONSTRAINT [FK_MARS_CMS_NECESSARY_FLEET_CAR_GROUPS] FOREIGN KEY ([CAR_CLASS_ID]) REFERENCES [dbo].[CAR_GROUPS] ([car_group_id]) ON DELETE CASCADE,
    CONSTRAINT [FK_MARS_CMS_NECESSARY_FLEET_CMS_LOCATION_GROUPS] FOREIGN KEY ([CMS_LOCATION_GROUP_ID]) REFERENCES [dbo].[CMS_LOCATION_GROUPS] ([cms_location_group_id]) ON DELETE CASCADE
);



