CREATE TABLE [dbo].[MARS_CMS_FORECAST_HISTORY] (
    [REP_DATE]                 DATETIME       NOT NULL,
    [COUNTRY]                  VARCHAR (10)   NULL,
    [CMS_LOCATION_GROUP_ID]    INT            NULL,
    [CAR_CLASS_ID]             INT            NULL,
    [CURRENT_ONRENT]           NUMERIC (9, 2) NULL,
    [ONRENT_LY]                NUMERIC (9, 2) NULL,
    [AVAILABLE_FLEET]          NUMERIC (9, 2) NULL,
    [OPERATIONAL_FLEET]        NUMERIC (9, 2) NULL,
    [TOTAL_FLEET]              NUMERIC (9, 2) NULL,
    [FLEET_UTILISATION_FROZEN] NUMERIC (5, 2) NULL,
    [FLEET_NONREV_FROZEN]      NUMERIC (5, 2) NULL,
    [FLEET_MOVEMENT_FROZEN]    INT            NULL,
    [CMS_CONSTRAINED_FROZEN]   NUMERIC (9, 2) NULL,
    [CMS_UNCONSTRAINED_FROZEN] NUMERIC (9, 2) NULL,
    [CMS_CONSTRAINED]          NUMERIC (9, 2) NULL,
    [CMS_UNCONSTRAINED]        NUMERIC (9, 2) NULL,
    [CMS_CONSTRAINED_WK1]      NUMERIC (9, 2) NULL,
    [CMS_UNCONSTRAINED_WK1]    NUMERIC (9, 2) NULL,
    [CMS_CONSTRAINED_WK2]      NUMERIC (9, 2) NULL,
    [CMS_UNCONSTRAINED_WK2]    NUMERIC (9, 2) NULL,
    [CMS_CONSTRAINED_WK3]      NUMERIC (9, 2) NULL,
    [CMS_UNCONSTRAINED_WK3]    NUMERIC (9, 2) NULL,
    [CMS_CONSTRAINED_WK4]      NUMERIC (9, 2) NULL,
    [CMS_UNCONSTRAINED_WK4]    NUMERIC (9, 2) NULL,
    [CMS_CONSTRAINED_WK5]      NUMERIC (9, 2) NULL,
    [CMS_UNCONSTRAINED_WK5]    NUMERIC (9, 2) NULL,
    [CMS_CONSTRAINED_WK6]      NUMERIC (9, 2) NULL,
    [CMS_UNCONSTRAINED_WK6]    NUMERIC (9, 2) NULL,
    [CMS_CONSTRAINED_WK7]      NUMERIC (9, 2) NULL,
    [CMS_UNCONSTRAINED_WK7]    NUMERIC (9, 2) NULL,
    [CMS_CONSTRAINED_WK8]      NUMERIC (9, 2) NULL,
    [CMS_UNCONSTRAINED_WK8]    NUMERIC (9, 2) NULL,
    [ADJUSTMENT_TD]            NUMERIC (9, 2) NULL,
    [ADJUSTMENT_BU1]           NUMERIC (9, 2) NULL,
    [ADJUSTMENT_BU2]           NUMERIC (9, 2) NULL,
    [ADJUSTMENT_RC]            NUMERIC (9, 2) NULL,
    [RowId]                    INT            IDENTITY (1, 1) NOT NULL,
    CONSTRAINT [PK_MARS_CMS_FORECAST_HISTORY] PRIMARY KEY NONCLUSTERED ([RowId] ASC),
    CONSTRAINT [FK_MARS_CMS_FORECAST_HISTORY_CAR_GROUPS] FOREIGN KEY ([CAR_CLASS_ID]) REFERENCES [dbo].[CAR_GROUPS] ([car_group_id]) ON DELETE CASCADE,
    CONSTRAINT [FK_MARS_CMS_FORECAST_HISTORY_CMS_LOCATION_GROUPS] FOREIGN KEY ([CMS_LOCATION_GROUP_ID]) REFERENCES [dbo].[CMS_LOCATION_GROUPS] ([cms_location_group_id]) ON DELETE CASCADE,
    CONSTRAINT [FK_MARS_CMS_FORECAST_HISTORY_COUNTRIES] FOREIGN KEY ([COUNTRY]) REFERENCES [dbo].[COUNTRIES] ([country])
);




GO
CREATE CLUSTERED INDEX [idx_rep_date_cms_his]
    ON [dbo].[MARS_CMS_FORECAST_HISTORY]([REP_DATE] ASC);

