CREATE TABLE [dbo].[MODELCODES] (
    [MODEL_ID] BIGINT       IDENTITY (1, 1) NOT NULL,
    [COUNTRY]  VARCHAR (10) NOT NULL,
    [MODEL]    VARCHAR (50) NOT NULL,
    [ACTIVE]   BIT          NULL,
    CONSTRAINT [PK_MODELCODES] PRIMARY KEY CLUSTERED ([MODEL_ID] ASC),
    CONSTRAINT [FK_MODELCODES_COUNTRIES] FOREIGN KEY ([COUNTRY]) REFERENCES [dbo].[COUNTRIES] ([country])
);


GO
CREATE NONCLUSTERED INDEX [Country]
    ON [dbo].[MODELCODES]([COUNTRY] ASC) WITH (ALLOW_PAGE_LOCKS = OFF);

