CREATE TABLE [dbo].[RESERVATIONS_EUROPE_ACTUAL_QUERY_TABLE] (
    [IMPORTTIME]       DATETIME      NOT NULL,
    [REP_YEAR]         AS            (datepart(year,[IMPORTTIME])),
    [REP_MONTH]        AS            (right('0'+rtrim(datepart(month,[IMPORTTIME])),(2))),
    [COUNTRY]          AS            ([dbo].[fnPoolingREALocationHierarchy]([dbo].[fnGetResRentLocFromResLoc]([res_loc]),'COUNTRY')),
    [CMS_POOL]         AS            ([dbo].[fnPoolingREALocationHierarchy]([dbo].[fnGetResRentLocFromResLoc]([res_loc]),'CMS_POOL')),
    [CMS_LOC_GRP]      AS            ([dbo].[fnPoolingREALocationHierarchy]([dbo].[fnGetResRentLocFromResLoc]([res_loc]),'CMS_LOC_GRP')),
    [OPS_REGION]       AS            ([dbo].[fnPoolingREALocationHierarchy]([dbo].[fnGetResRentLocFromResLoc]([res_loc]),'OPS_REGION')),
    [OPS_AREA]         AS            ([dbo].[fnPoolingREALocationHierarchy]([dbo].[fnGetResRentLocFromResLoc]([res_loc]),'OPS_AREA')),
    [CAR_SEGMENT]      AS            ([dbo].[fnPoolingREACarGroupHierarchy]([dbo].[fnGetResGRinclGoldupgrFromN1typeAndGsAndResVehClass]([n1type],[gs],[res_veh_class],[dbo].[fnPoolingREALocationHierarchy]([dbo].[fnGetResRentLocFromResLoc]([res_loc]),'COUNTRY')),[dbo].[fnPoolingREALocationHierarchy]([dbo].[fnGetResRentLocFromResLoc]([res_loc]),'COUNTRY'),'CAR_SEGMENT')),
    [CAR_CLASS]        AS            ([dbo].[fnPoolingREACarGroupHierarchy]([dbo].[fnGetResGRinclGoldupgrFromN1typeAndGsAndResVehClass]([n1type],[gs],[res_veh_class],[dbo].[fnPoolingREALocationHierarchy]([dbo].[fnGetResRentLocFromResLoc]([res_loc]),'COUNTRY')),[dbo].[fnPoolingREALocationHierarchy]([dbo].[fnGetResRentLocFromResLoc]([res_loc]),'COUNTRY'),'CAR_CLASS')),
    [CARVAN]           AS            ([dbo].[fnPoolingREACarGroupHierarchy]([dbo].[fnGetResGRinclGoldupgrFromN1typeAndGsAndResVehClass]([n1type],[gs],[res_veh_class],[dbo].[fnPoolingREALocationHierarchy]([dbo].[fnGetResRentLocFromResLoc]([res_loc]),'COUNTRY')),[dbo].[fnPoolingREALocationHierarchy]([dbo].[fnGetResRentLocFromResLoc]([res_loc]),'COUNTRY'),'CARVAN')),
    [RES_ID_NBR]       VARCHAR (14)  NULL,
    [RES_LOC]          VARCHAR (10)  NULL,
    [RENT_LOC]         AS            ([dbo].[fnGetResRentLocFromResLoc]([res_loc])),
    [RTRN_LOC]         VARCHAR (10)  NULL,
    [ICIND]            VARCHAR (2)   NULL,
    [ONEWAY]           AS            ([dbo].[fnGetResOnewayFromRentLocAndRtrnLoc]([dbo].[fnGetResRentLocFromResLoc]([res_loc]),[rtrn_loc])),
    [RS_ARRIVAL_DATE]  DATETIME      NULL,
    [RS_ARRIVAL_TIME]  DATETIME      NULL,
    [RTRN_DATE]        DATETIME      NULL,
    [RTRN_TIME]        DATETIME      NULL,
    [RES_DAYS]         FLOAT (53)    NULL,
    [RES_VEH_CLASS]    VARCHAR (2)   NULL,
    [GR_INCL_GOLDUPGR] AS            ([dbo].[fnGetResGRinclGoldupgrFromN1typeAndGsAndResVehClass]([n1type],[gs],[res_veh_class],[dbo].[fnPoolingREALocationHierarchy]([dbo].[fnGetResRentLocFromResLoc]([res_loc]),'COUNTRY'))),
    [RATE_QUOTED]      VARCHAR (15)  NULL,
    [SUBTOTAL_2]       FLOAT (53)    NULL,
    [MOP]              VARCHAR (10)  NULL,
    [PREPAID]          VARCHAR (2)   NULL,
    [NEVERLOST]        VARCHAR (2)   NULL,
    [PREDELIVERY]      VARCHAR (2)   NULL,
    [CUST_NAME]        VARCHAR (28)  NULL,
    [PHONE]            VARCHAR (25)  NULL,
    [CDPID_NBR]        VARCHAR (10)  NULL,
    [CNTID_NBR]        VARCHAR (10)  NULL,
    [NO1_CLUB_GOLD]    VARCHAR (10)  NULL,
    [TACO]             VARCHAR (10)  NULL,
    [FLIGHT_NBR]       VARCHAR (10)  NULL,
    [REMARKS]          VARCHAR (100) NULL,
    [GS]               VARCHAR (2)   NULL,
    [N1TYPE]           VARCHAR (2)   NULL,
    [DATE_SOLD]        DATETIME      NULL,
    [R1]               VARCHAR (25)  NULL,
    [R2]               VARCHAR (25)  NULL,
    [R3]               VARCHAR (25)  NULL,
    [TS]               DATETIME      NULL,
    [CO_HOURS]         AS            ([dbo].[fnGetResCOHoursForImporttimeAndRsarrivaldateAndRsarrivaltime]([importtime],[rs_arrival_date],[rs_arrival_time])),
    [CO_DAYS]          AS            ([dbo].[fnGetResCODaysForImporttimeAndRsarrivaldate]([importtime],[rs_arrival_date])),
    [CI_HOURS]         AS            ([dbo].[fnGetResCIHoursForImporttimeAndRtrndateAndRtrntime]([importtime],[rtrn_date],[rtrn_time])),
    [CI_HOURS_OFFSET]  AS            ([dbo].[fnGetResCIHoursForImporttimeAndRtrndateAndRtrntime]([importtime],[rtrn_date],[rtrn_time])),
    [CI_DAYS]          AS            ([dbo].[fnGetResCIDaysForImporttimeAndRtrndate]([importtime],[rtrn_date]))
);

